name: training_member
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.1+1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  get: ^4.6.5
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
  uses-material-design: true

